function s = setup
% s = setup returns the settings for run_exp.
%
% % Settings %
%
%   % General
%   s.rng_state    - state of random number generator (not mandatory)
%   s.file_prefix  - prefix for saving files (e.g., analog input recording)
%   s.pause_num    - number of pauses (+ 1 = number of blocks)
%
%   % Stimuli   
%   s.stim_types   - stimulus typ labels (0 - none; 1 - near)
%   s.stim_types_num - number of stimulus types (should be a multiple of s.stim_steps)
%   s.near_d       - detection probability for stimulus s.stim_types(2)
%   s.near_name    - name for stimulus intensity in dialog
%   s.stim_steps   - intensity steps as factors of near- and supra-threshold intensity
%   % s.stim_p_steps - perfomance level steps in relation to s.near_p and s.supra_p
%   s.pulse_t      - duration of stimuls (rectangular pulse) in ms
%   s.pre_pulse_t  - duration of before stimulus (rectangular pulse) in ms
%   s.wave_t       - duration of waveform with rectangular pulse in ms
%   s.stim_dec     - number of decimal digits of intensity in mA (doc dlg_intensities)
%   s.stim_max     - maximum possible stimulus intensity in mA
%   s.TTL_t        - TTL pulse length (1 ms)
%   s.TTL_V        - TTL pulse amplitude (5 V)
% 
%   % Trial
%   s.get_flip_i   - number of samples for initial flip interval estimation with Screen('GetFlipInterval')
%   s.fix_t        - min/max vector for duration of fixation cross in s
%   s.cue_t        - duration of stimulus cue in s
%   s.stim_delay   - min/max vector for pseudo-randomized stimulus delay in s
%   s.stim2resp    - pause between stimulus cue and response screen in s
%   s.resp_window  - 'variable'/'fixed' - stop/continue after first button press
%   s.resp1_max_t  - maximum response time 1 in s
%   s.resp2_max_t  - maximum response time 2 in s
%   s.resp_p_min_t - minimum time left to show response pause screen in s
%
%   % Screen design
%   s.window_color - screen background rgb color vector
% 
%   % Text
%   s.txt_color    - text rgb color vector
%   s.txt_font     - font type
%   s.txt_size     - font size for response screens
%   s.cue_size     - font size for fix, cue and pause screens
% 
%   % Messages
%   s.fix          - fixation symbol (e.g., '+')
%   s.cue          - stimulus cue symbol (e.g., '~+~')
%   s.resp1_txt    - yes/no response text options, yes-no-order important, e.g. ['J'; 'N']
%   s.resp2_txt    - confidence response text options
%   s.resp1_offset - 1st response text offset left from screen center
%   s.ITI_cue      - inter trial interval symbol
%   s.pause_msg    - message on pause screen
% 
%   % Buttons
%   s.lpt_adr1     - parallel port address (see device manager - LPT1 details - resources)
%   s.lpt_adr2     - as above but 'I/O Range' #2
%   s.lpt_dir      - parallel port direction ('bi' or 'uni')
%   s.btn_resp1    - button codes for yes/no response
%   s.btn_resp2    - button codes for confidence response
%   s.btn_esc      - button code for quiting experiment
%
%   % Instruction
%   s.instr_dir    - instruction directory with condition subdirectories
%                     (relative to directory of nt_exp.m)
%   s.instr_subdir_wildcard    - instruction subdirectory wildcard
%   s.instr_img_wildcard       - filename wildcard of instruction image files
%
%
% Author:           Martin Grund
% Last update:      December 18, 2018

% Modified by Busra Cilburunoglu and Lioba Enk
% Last update: Oct 10, 2025

%% Settings

%% General
% s.rng_state = sum(100*clock); % If not defined, generated by run_exp
s.file_prefix = 'respirationAdj1_';

%% Stimuli
s.stim_types = [0 1];
s.near_d = .65;
s.near_name = 'Near-threshold';
s.stim_steps = 1; % [.95 1 1.05];
s.pulse_t = 0.2;
s.pre_pulse_t = 1;
s.wave_t = 3; % ms [s.pre_pulse_t + s.TTL_t + x]
s.stim_dec = 2;
s.stim_max = 7;

s.TTL_t = 1;
s.TTL_V = 5;

%% Trial
s.get_flip_i = 200;

%% Pre-Trial Information for Each Condition and Trial Settings

% RhyF: Rhythmic Fast
s.RhyF.start_trials_per_block = 6;
s.RhyF.start_trials_stim_types_num = [2 4];
s.RhyF.start_trials_fix_t = 3.500;

% RhyS: Rhythmic Slow
s.RhyS.start_trials_per_block = 10;
s.RhyS.start_trials_stim_types_num = [3 7];
s.RhyS.start_trials_fix_t = 1.000;

% RanS: Random Slow
s.RanS.start_trials_per_block = 10;
s.RanS.start_trials_stim_types_num = [3 7];
s.RanS.start_trials_fix_t = 1.000;

%% Define Main Experiment Conditions and Trial Settings


% RhyF: Rhythmic Fast
s.RhyF.name = 'RhyF';
s.RhyF.trials_per_block = 160; 
s.RhyF.num_blocks = 2;
s.RhyF.stim_types_num = [40 120];
s.RhyF.fix_t = [0.500 1.500];

% RhyS: Rhythmic Slow
s.RhyS.name = 'RhyS';
s.RhyS.trials_per_block = 80;
s.RhyS.num_blocks = 4;
s.RhyS.stim_types_num = [20 60];
s.RhyS.fix_t = [3.000 4.000];

% RanS: Random Slow
s.RanS.name = 'RanS';
s.RanS.trials_per_block = 80;
s.RanS.num_blocks = 4;
s.RanS.stim_types_num = [20 60];
s.RanS.fix_t = [0.500 6.500];

s.blocks = sum([s.RhyF.num_blocks, s.RhyS.num_blocks, s.RanS.num_blocks]);



%% Trial 
s.cue_t = 1.000;
s.stim_delay = [0.7 0.7];
s.resp_window = 'variable';
s.resp1_max_t = 1.500;
s.resp2_max_t = 1.500;
%s.resp_p_min_t = 0.300;

% Screen number write
s.screenNumber = 0;
%% Screen design
s.window_color = [200 200 200];%[250 250 250]; % grey98 (very light grey)

%% Text
s.txt_color = [40 40 40]; % grey15-16 (anthracite)
s.txt_font = 'Arial';
s.txt_size = 105;
s.cue_size = 125;
s.cue_color = [255 126 121]; % salmon

%% Messages
s.fix = '+';
s.cue = '+';
s.resp1_txt = ['J'; 'N'];   % Ja - Nein
s.resp2_txt = ['S'; 'U'];   % Ja - Nein
s.resp1_offset = 30;
s.pause_msg = '# Pause #\n\n\nWeiter mit beliebiger Taste';

%% EEG trigger numbers
s.fixOnset = 10; 
s.cueOnset = 20;

%% Buttons

try
    IOPort('Close', S_PORT);
    disp('Previous serial port closed')
catch
    disp('Serial port could not be closed. Not open yet?')
end 
IOPort('CloseAll');
[s_port errmsg] = IOPort('OpenSerialPort', 'COM2');
IOPort('ConfigureSerialPort', s_port, 'BaudRate=19200')
IOPort('ConfigureSerialPort', s_port, 'DataBits=8')
IOPort('ConfigureSerialPort', s_port, 'StopBits=1')
S_PORT = s_port;
s.s_port = s_port;
s.lpt_adr1 = hex2dec('D010');
%s.lpt_adr2 = hex2dec('0378');
s.lpt_dir = 'bi';
s.trigger_length = 0.01;
s.debounceDelay = 0.025;
s.btn_resp1 = [1 2];
s.btn_resp2 = [1 2];
s.btn_esc = 27;


%% Instruction
s.instr_dir = '/instr/';
s.instr_subdir_wildcard = 'condition_*';
s.instr_img_wildcard = 'instr*.png';
